-- Versioned, per-crop interpretation profile. A new version supersedes the
-- previous one rather than overwriting it, so historical assessments keep
-- referencing the profile version that produced them. See ADR-021.
CREATE TABLE crop_monitoring_profile (
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id                             BIGINT NOT NULL REFERENCES crop(id),
    version                             INTEGER NOT NULL,
    preferred_temperature_min_celsius   DOUBLE PRECISION NOT NULL,
    preferred_temperature_max_celsius   DOUBLE PRECISION NOT NULL,
    temperature_excursion_seconds       BIGINT NOT NULL,
    temperature_recovery_seconds        BIGINT NOT NULL,
    soil_moisture_strategy              VARCHAR(50) NOT NULL,
    soil_dry_threshold_index            DOUBLE PRECISION,
    soil_wet_threshold_index            DOUBLE PRECISION,
    enabled                             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                          TIMESTAMPTZ NOT NULL,
    created_by                          VARCHAR(255) NOT NULL,
    source_notes                        TEXT,
    supersedes_profile_id               BIGINT REFERENCES crop_monitoring_profile(id),
    CONSTRAINT ck_crop_monitoring_profile_temperature_range
        CHECK (preferred_temperature_min_celsius < preferred_temperature_max_celsius)
);

CREATE INDEX idx_crop_monitoring_profile_crop ON crop_monitoring_profile(crop_id, version DESC);

-- At most one enabled profile per crop; older versions remain as history.
CREATE UNIQUE INDEX uq_crop_monitoring_profile_enabled
    ON crop_monitoring_profile(crop_id)
    WHERE enabled = TRUE;
