-- Which crop a physical probe currently serves. Deliberately separate from
-- sensor_calibration: sensor identity and crop assignment are independent
-- facts that change independently (ADR-018's principle, ADR-022's modelling).
-- No FK from soil_moisture_reading - raw ingestion must keep working
-- regardless of domain state; assignment resolves by sensor_id at query time.
CREATE TABLE crop_sensor_assignment (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id                   VARCHAR(255) NOT NULL,
    crop_id                     BIGINT NOT NULL REFERENCES crop(id),
    version                     INTEGER NOT NULL,
    assigned_at                 TIMESTAMPTZ NOT NULL,
    assigned_by                 VARCHAR(255) NOT NULL,
    valid_to                    TIMESTAMPTZ,
    notes                       TEXT,
    supersedes_assignment_id    BIGINT REFERENCES crop_sensor_assignment(id)
);

CREATE INDEX idx_crop_sensor_assignment_sensor ON crop_sensor_assignment(sensor_id, version DESC);
CREATE INDEX idx_crop_sensor_assignment_crop ON crop_sensor_assignment(crop_id);

-- A sensor serves at most one crop at a time; superseded rows carry valid_to.
CREATE UNIQUE INDEX uq_crop_sensor_assignment_current
    ON crop_sensor_assignment(sensor_id)
    WHERE valid_to IS NULL;
