-- Calibration belongs to the physical probe, not the crop - a probe moved to
-- a different pot keeps its calibration. Versioned so that recalibrating never
-- changes the meaning of a historical assessment. See ADR-022.
CREATE TABLE sensor_calibration (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id                   VARCHAR(255) NOT NULL,
    version                     INTEGER NOT NULL,
    dry_reference_raw           INTEGER NOT NULL,
    wet_reference_raw           INTEGER NOT NULL,
    calibrated_at               TIMESTAMPTZ NOT NULL,
    calibrated_by               VARCHAR(255) NOT NULL,
    method                      VARCHAR(255),
    notes                       TEXT,
    valid_to                    TIMESTAMPTZ,
    supersedes_calibration_id   BIGINT REFERENCES sensor_calibration(id),
    -- A degenerate calibration (equal references) would make the moisture
    -- index formula divide by zero; rejected at the database level too.
    CONSTRAINT ck_sensor_calibration_references_differ
        CHECK (dry_reference_raw <> wet_reference_raw)
);

CREATE INDEX idx_sensor_calibration_sensor ON sensor_calibration(sensor_id, version DESC);

CREATE UNIQUE INDEX uq_sensor_calibration_current
    ON sensor_calibration(sensor_id)
    WHERE valid_to IS NULL;
