-- Append-only history for every assessment transition (ADR-021). Each row
-- carries a FULL snapshot rather than a diff, which is what makes the mutable
-- `assessment` table genuinely rebuildable from this history - and therefore
-- legitimately a projection rather than a source of truth.
--
-- Applies to every assessment code, including the four pre-existing
-- zone-level rules, so there is exactly one assessment lifecycle in the system
-- rather than two running in parallel.
CREATE TABLE assessment_lifecycle_event (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id               BIGINT NOT NULL REFERENCES assessment(id),
    event_type                  VARCHAR(50) NOT NULL,
    correlation_key             VARCHAR(500) NOT NULL,
    greenhouse_id               VARCHAR(255) NOT NULL,
    zone_id                     VARCHAR(255),
    device_id                   VARCHAR(255),
    crop_id                     BIGINT,
    scope_type                  VARCHAR(50) NOT NULL,
    scope_id                    VARCHAR(255) NOT NULL,
    code                        VARCHAR(100) NOT NULL,
    severity                    VARCHAR(50) NOT NULL,
    status                      VARCHAR(50) NOT NULL,
    message                     TEXT NOT NULL,
    evidence_json               JSONB NOT NULL,
    rule_id                     VARCHAR(255) NOT NULL,
    rule_version                INTEGER NOT NULL,
    monitoring_profile_id       BIGINT,
    monitoring_profile_version  INTEGER,
    calibration_id              BIGINT,
    calibration_version         INTEGER,
    first_detected_at           TIMESTAMPTZ NOT NULL,
    last_detected_at            TIMESTAMPTZ NOT NULL,
    resolved_at                 TIMESTAMPTZ,
    occurred_at                 TIMESTAMPTZ NOT NULL,
    actor_type                  VARCHAR(50) NOT NULL,
    actor_id                    VARCHAR(255)
);

CREATE INDEX idx_assessment_lifecycle_event_assessment
    ON assessment_lifecycle_event(assessment_id, occurred_at);

CREATE INDEX idx_assessment_lifecycle_event_correlation
    ON assessment_lifecycle_event(correlation_key, occurred_at);

CREATE INDEX idx_assessment_lifecycle_event_occurred
    ON assessment_lifecycle_event(occurred_at DESC);
