-- The correlation root for one actionable condition and everything that
-- responds to it (ADR-021). Lifecycle status is NOT stored here - it is
-- projected from the immutable event history.
CREATE TABLE care_loop (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    primary_subject_type    VARCHAR(50) NOT NULL,
    primary_subject_id      VARCHAR(255) NOT NULL,
    condition_type          VARCHAR(100) NOT NULL,
    correlation_key         VARCHAR(500) NOT NULL,
    opened_at               TIMESTAMPTZ NOT NULL,
    closed_at               TIMESTAMPTZ,
    created_by              VARCHAR(50) NOT NULL
);

CREATE INDEX idx_care_loop_subject ON care_loop(primary_subject_type, primary_subject_id);
CREATE INDEX idx_care_loop_open ON care_loop(closed_at) WHERE closed_at IS NULL;

-- Duplicate open loops for the same condition are prevented at the database
-- level, mirroring uq_assessment_active_correlation's approach.
CREATE UNIQUE INDEX uq_care_loop_open_correlation
    ON care_loop(correlation_key)
    WHERE closed_at IS NULL;

-- Which assessments belong to a loop. A loop may link several assessments -
-- e.g. one greenhouse ventilation loop covering every crop's temperature
-- assessment, producing one command rather than six duplicates.
CREATE TABLE care_loop_assessment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_loop_id    BIGINT NOT NULL REFERENCES care_loop(id),
    assessment_id   BIGINT NOT NULL REFERENCES assessment(id),
    linked_at       TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uq_care_loop_assessment ON care_loop_assessment(care_loop_id, assessment_id);
CREATE INDEX idx_care_loop_assessment_assessment ON care_loop_assessment(assessment_id);
