-- Loop-level lifecycle transitions that are not implied by a decision,
-- command, execution or outcome event - principally OPENED, BLOCKED and
-- CLOSED. Closure is not unambiguously derivable from an outcome alone (an
-- INCONCLUSIVE outcome may leave the loop open awaiting a later observation),
-- so it is recorded explicitly. Append-only. See ADR-021.
CREATE TABLE care_loop_status_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_loop_id    BIGINT NOT NULL REFERENCES care_loop(id),
    status          VARCHAR(50) NOT NULL,
    reason_code     VARCHAR(100),
    reason_text     TEXT,
    actor_type      VARCHAR(50) NOT NULL,
    actor_id        VARCHAR(255),
    occurred_at     TIMESTAMPTZ NOT NULL,
    request_id      VARCHAR(255)
);

CREATE INDEX idx_care_loop_status_event_loop
    ON care_loop_status_event(care_loop_id, occurred_at);
