-- Whether a record is relevant to a particular care loop. Scope belongs to
-- the loop-record RELATIONSHIP, not to the record globally, and is deliberately
-- separate from lifecycle and approval state: a rejected decision or a resolved
-- assessment normally stays IN_SCOPE as historical evidence (ADR-021 section
-- 5.4). Effective scope is the latest event for a given loop-record pair.
--
-- Most rows here are written automatically by ScopeService when a record joins
-- a loop; human overrides are exceptional and always carry a reason.
CREATE TABLE loop_record_scope_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_loop_id    BIGINT NOT NULL REFERENCES care_loop(id),
    record_type     VARCHAR(50) NOT NULL,
    record_id       BIGINT NOT NULL,
    scope           VARCHAR(50) NOT NULL,
    reason_code     VARCHAR(100),
    reason_text     TEXT,
    actor_type      VARCHAR(50) NOT NULL,
    actor_id        VARCHAR(255),
    occurred_at     TIMESTAMPTZ NOT NULL,
    request_id      VARCHAR(255)
);

CREATE INDEX idx_loop_record_scope_event_lookup
    ON loop_record_scope_event(care_loop_id, record_type, record_id, occurred_at DESC);
