-- An immutable proposed response to one or more in-scope assessments.
-- Never updated: an amended decision is a NEW row with supersedes_decision_id
-- pointing at the original, which is preserved intact (ADR-021).
CREATE TABLE decision (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_loop_id            BIGINT NOT NULL REFERENCES care_loop(id),
    action_type             VARCHAR(100) NOT NULL,
    parameters_json         JSONB NOT NULL,
    rationale               TEXT NOT NULL,
    expected_effect         TEXT NOT NULL,
    evaluation_method       VARCHAR(100) NOT NULL,
    evaluation_delay_seconds    BIGINT,
    evaluation_window_seconds   BIGINT,
    success_criteria        TEXT,
    proposed_by             VARCHAR(50) NOT NULL,
    proposed_by_actor_id    VARCHAR(255),
    proposed_at             TIMESTAMPTZ NOT NULL,
    supersedes_decision_id  BIGINT REFERENCES decision(id)
);

CREATE INDEX idx_decision_care_loop ON decision(care_loop_id, proposed_at DESC);

-- Which assessments a decision responds to.
CREATE TABLE decision_assessment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id     BIGINT NOT NULL REFERENCES decision(id),
    assessment_id   BIGINT NOT NULL REFERENCES assessment(id)
);

CREATE UNIQUE INDEX uq_decision_assessment ON decision_assessment(decision_id, assessment_id);

-- Optional link to the goals a decision serves.
CREATE TABLE decision_goal (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id BIGINT NOT NULL REFERENCES decision(id),
    goal_id     BIGINT NOT NULL REFERENCES goal(id)
);

CREATE UNIQUE INDEX uq_decision_goal ON decision_goal(decision_id, goal_id);
