-- PROPOSED / APPROVED / REJECTED / SUPERSEDED. Approval is an appended event,
-- never a status column mutated in place. A command may only be generated from
-- a decision whose latest event is APPROVED (ADR-021).
CREATE TABLE decision_lifecycle_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id     BIGINT NOT NULL REFERENCES decision(id),
    event_type      VARCHAR(50) NOT NULL,
    reason_text     TEXT,
    actor_type      VARCHAR(50) NOT NULL,
    actor_id        VARCHAR(255),
    occurred_at     TIMESTAMPTZ NOT NULL,
    request_id      VARCHAR(255)
);

CREATE INDEX idx_decision_lifecycle_event_decision
    ON decision_lifecycle_event(decision_id, occurred_at);
