-- A concrete instruction generated from an APPROVED decision. Immutable: a
-- changed instruction is a replacement command, not an edit (ADR-021).
--
-- target_type is HUMAN for every command in this version. The column exists
-- rather than being hardcoded so that a future actuator target is a new value
-- rather than a schema change - but no actuator command may be created today.
CREATE TABLE command (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_loop_id            BIGINT NOT NULL REFERENCES care_loop(id),
    decision_id             BIGINT NOT NULL REFERENCES decision(id),
    command_type            VARCHAR(100) NOT NULL,
    target_type             VARCHAR(50) NOT NULL,
    target_id               VARCHAR(255),
    parameters_json         JSONB NOT NULL,
    issued_at               TIMESTAMPTZ NOT NULL,
    expires_at              TIMESTAMPTZ,
    supersedes_command_id   BIGINT REFERENCES command(id),
    CONSTRAINT ck_command_target_is_human CHECK (target_type = 'HUMAN')
);

CREATE INDEX idx_command_care_loop ON command(care_loop_id, issued_at DESC);
CREATE INDEX idx_command_decision ON command(decision_id);

-- Exactly one command per decision: approval issues a command once, and a
-- retried approval must not produce a second one.
CREATE UNIQUE INDEX uq_command_decision ON command(decision_id);
