-- ISSUED / ACKNOWLEDGED / DEFERRED / DECLINED / CANCELLED / EXPIRED.
-- Append-only; the command row itself is never mutated (ADR-021).
CREATE TABLE command_lifecycle_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id      BIGINT NOT NULL REFERENCES command(id),
    event_type      VARCHAR(50) NOT NULL,
    reason_text     TEXT,
    deferred_until  TIMESTAMPTZ,
    actor_type      VARCHAR(50) NOT NULL,
    actor_id        VARCHAR(255),
    occurred_at     TIMESTAMPTZ NOT NULL,
    request_id      VARCHAR(255)
);

CREATE INDEX idx_command_lifecycle_event_command
    ON command_lifecycle_event(command_id, occurred_at);
