-- What the human actually did - deliberately NOT what the command requested.
-- The requested parameters stay on the command; actual_parameters_json records
-- reality, so "asked for 300ml, gave 200ml" is preserved as two distinct facts
-- rather than one overwritten one (ADR-021).
--
-- Immutable: a correction is a new row with corrects_execution_id set.
CREATE TABLE execution (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_loop_id            BIGINT NOT NULL REFERENCES care_loop(id),
    command_id              BIGINT NOT NULL REFERENCES command(id),
    result                  VARCHAR(50) NOT NULL,
    actual_parameters_json  JSONB,
    performed_by            VARCHAR(50) NOT NULL,
    performed_by_actor_id   VARCHAR(255),
    started_at              TIMESTAMPTZ,
    completed_at            TIMESTAMPTZ NOT NULL,
    notes                   TEXT,
    recorded_at             TIMESTAMPTZ NOT NULL,
    request_id              VARCHAR(255),
    corrects_execution_id   BIGINT REFERENCES execution(id)
);

CREATE INDEX idx_execution_care_loop ON execution(care_loop_id, completed_at DESC);
CREATE INDEX idx_execution_command ON execution(command_id);
