-- An evidence-based evaluation of an execution against its decision's expected
-- effect. INCONCLUSIVE is a legitimate, expected result when the evidence
-- needed to judge simply is not available - the system never fabricates
-- success (ADR-021).
--
-- Immutable: a re-evaluation is a new row with supersedes_outcome_id set.
CREATE TABLE outcome (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    care_loop_id                BIGINT NOT NULL REFERENCES care_loop(id),
    decision_id                 BIGINT NOT NULL REFERENCES decision(id),
    command_id                  BIGINT NOT NULL REFERENCES command(id),
    execution_id                BIGINT NOT NULL REFERENCES execution(id),
    result                      VARCHAR(50) NOT NULL,
    evaluated_at                TIMESTAMPTZ NOT NULL,
    evaluation_window_start     TIMESTAMPTZ NOT NULL,
    evaluation_window_end       TIMESTAMPTZ NOT NULL,
    evidence_json               JSONB,
    summary                     TEXT NOT NULL,
    evaluated_by                VARCHAR(50) NOT NULL,
    evaluated_by_actor_id       VARCHAR(255),
    supersedes_outcome_id       BIGINT REFERENCES outcome(id)
);

CREATE INDEX idx_outcome_care_loop ON outcome(care_loop_id, evaluated_at DESC);
CREATE INDEX idx_outcome_execution ON outcome(execution_id);

-- Executions awaiting their evaluation window, polled by the outcome scheduler.
CREATE TABLE outcome_evaluation_schedule (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id        BIGINT NOT NULL REFERENCES execution(id),
    care_loop_id        BIGINT NOT NULL REFERENCES care_loop(id),
    evaluate_after      TIMESTAMPTZ NOT NULL,
    window_end          TIMESTAMPTZ NOT NULL,
    completed_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uq_outcome_evaluation_schedule_execution
    ON outcome_evaluation_schedule(execution_id);

CREATE INDEX idx_outcome_evaluation_schedule_pending
    ON outcome_evaluation_schedule(evaluate_after)
    WHERE completed_at IS NULL;
