-- A human reviewing, qualifying or disputing an outcome appends here. If the
-- review carries a corrected result, a NEW outcome row is created with
-- supersedes_outcome_id set - the original outcome is never overwritten
-- (ADR-021).
CREATE TABLE outcome_review_event (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outcome_id              BIGINT NOT NULL REFERENCES outcome(id),
    review_note             TEXT NOT NULL,
    disputed                BOOLEAN NOT NULL DEFAULT FALSE,
    additional_evidence_json JSONB,
    resulting_outcome_id    BIGINT REFERENCES outcome(id),
    actor_type              VARCHAR(50) NOT NULL,
    actor_id                VARCHAR(255),
    occurred_at             TIMESTAMPTZ NOT NULL,
    request_id              VARCHAR(255)
);

CREATE INDEX idx_outcome_review_event_outcome
    ON outcome_review_event(outcome_id, occurred_at);
