-- Every care-loop MCP write operation is idempotent (ADR-021). A retried
-- approval or watering confirmation must return the original result rather
-- than creating a second command or execution.
--
-- request_fingerprint is a hash of tool name + arguments: reusing a key with
-- different arguments is a caller bug, not a legitimate retry, and is rejected
-- rather than silently returning an unrelated stored result.
CREATE TABLE idempotent_request (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key     VARCHAR(255) NOT NULL,
    tool_name           VARCHAR(255) NOT NULL,
    request_fingerprint VARCHAR(128) NOT NULL,
    status              VARCHAR(50) NOT NULL,
    -- TEXT, not JSONB: this holds the already-serialized tool response that is
    -- handed straight back to the caller on a retry. It is never queried into,
    -- and typing it as JSONB would imply a queryability that is not provided.
    result_json         TEXT,
    created_at          TIMESTAMPTZ NOT NULL,
    completed_at        TIMESTAMPTZ
);

-- The unique constraint is what makes concurrent duplicate submissions safe:
-- the loser of the insert race reads the winner's result instead.
CREATE UNIQUE INDEX uq_idempotent_request_key ON idempotent_request(idempotency_key);
