-- One immutable structured briefing per greenhouse day.
--
-- Deliberately NOT unique on greenhouse_day: regenerating a day's briefing
-- creates a new version linked to the previous one via supersedes_snapshot_id,
-- rather than overwriting it. "One per scheduled occurrence" is enforced in
-- DailyBriefingService by checking before generating, which is also what makes
-- missed-run recovery idempotent after a restart.
CREATE TABLE daily_briefing_snapshot (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    greenhouse_day          DATE NOT NULL,
    scheduled_for           TIMESTAMPTZ NOT NULL,
    generated_at            TIMESTAMPTZ NOT NULL,
    window_start            TIMESTAMPTZ NOT NULL,
    window_end              TIMESTAMPTZ NOT NULL,
    snapshot_json           JSONB NOT NULL,
    missed_run_recovery     BOOLEAN NOT NULL DEFAULT FALSE,
    supersedes_snapshot_id  BIGINT REFERENCES daily_briefing_snapshot(id)
);

CREATE INDEX idx_daily_briefing_snapshot_day
    ON daily_briefing_snapshot(greenhouse_day DESC, generated_at DESC);
