-- Outbound notification: an append-only projection of care-loop and briefing
-- state. It never mutates the records it reports on (ADR-023).

-- An intent is an immutable statement that the platform decided a message
-- should be delivered. Rows are never updated or deleted in normal operation;
-- a correction is a new intent, not an edit.
CREATE TABLE notification_intent (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intent_type             VARCHAR(50) NOT NULL,
    priority                VARCHAR(50) NOT NULL,
    audience                VARCHAR(50) NOT NULL,
    care_loop_id            BIGINT REFERENCES care_loop(id),
    briefing_snapshot_id    BIGINT REFERENCES daily_briefing_snapshot(id),
    source_type             VARCHAR(100) NOT NULL,
    source_id               VARCHAR(255) NOT NULL,
    deduplication_key       VARCHAR(500) NOT NULL,
    payload_json            JSONB NOT NULL,
    not_before              TIMESTAMPTZ NOT NULL,
    expires_at              TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL,
    -- A business notification concerns exactly one anchor. Enforced here rather
    -- than only in code because the deduplication key derives from it.
    CONSTRAINT ck_notification_intent_single_anchor CHECK (
        (care_loop_id IS NOT NULL AND briefing_snapshot_id IS NULL)
        OR (care_loop_id IS NULL AND briefing_snapshot_id IS NOT NULL)
    )
);

-- The real idempotency guarantee. Repeated five-minute sweeps of unchanged
-- state compute the same key and lose the insert race harmlessly, which is why
-- policy never needs to ask "did I already send this?"
CREATE UNIQUE INDEX uq_notification_intent_deduplication
    ON notification_intent(deduplication_key);

CREATE INDEX idx_notification_intent_care_loop ON notification_intent(care_loop_id)
    WHERE care_loop_id IS NOT NULL;
CREATE INDEX idx_notification_intent_pending ON notification_intent(not_before);
CREATE INDEX idx_notification_intent_created ON notification_intent(created_at DESC);

-- One immutable row per delivery transition. Current delivery state is derived
-- from the latest event; earlier failed attempts are never modified on retry.
CREATE TABLE notification_delivery_event (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_intent_id  BIGINT NOT NULL REFERENCES notification_intent(id),
    channel                 VARCHAR(50) NOT NULL,
    event_type              VARCHAR(50) NOT NULL,
    attempt_number          INTEGER NOT NULL,
    recipient               VARCHAR(500) NOT NULL,
    occurred_at             TIMESTAMPTZ NOT NULL,
    provider_message_id     VARCHAR(500),
    -- Sanitised classification only. Credentials must never reach these columns.
    error_code              VARCHAR(100),
    error_message           TEXT,
    next_attempt_at         TIMESTAMPTZ,
    metadata_json           JSONB
);

CREATE INDEX idx_notification_delivery_event_intent
    ON notification_delivery_event(notification_intent_id, occurred_at);

CREATE INDEX idx_notification_delivery_event_retry
    ON notification_delivery_event(next_attempt_at)
    WHERE next_attempt_at IS NOT NULL;
