-- A greenhouse day now has two briefings: one at 06:00 read before leaving the
-- house, and one at 19:00 read on getting home, when there is still time to act
-- (ADR-033).
--
-- Uniqueness stays out of the database on purpose. As with the original table,
-- "one per scheduled occurrence" is enforced in DailyBriefingService, because
-- regenerating a briefing must still be able to create a superseding version
-- rather than being blocked by a constraint (ADR-021).
ALTER TABLE daily_briefing_snapshot
    ADD COLUMN edition VARCHAR(20) NOT NULL DEFAULT 'MORNING';

-- Every existing row was generated by the single 06:00 schedule, so the default
-- is not a guess - it is what those briefings actually were.

DROP INDEX IF EXISTS idx_daily_briefing_snapshot_day;

CREATE INDEX idx_daily_briefing_snapshot_day_edition
    ON daily_briefing_snapshot(greenhouse_day DESC, edition, generated_at DESC);
