CREATE TABLE assessment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlation_key     VARCHAR(500) NOT NULL,
    greenhouse_id       VARCHAR(255) NOT NULL,
    zone_id             VARCHAR(255),
    device_id           VARCHAR(255),
    scope_type          VARCHAR(50) NOT NULL,
    scope_id            VARCHAR(255) NOT NULL,
    code                VARCHAR(100) NOT NULL,
    severity            VARCHAR(50) NOT NULL,
    status              VARCHAR(50) NOT NULL,
    message             TEXT NOT NULL,
    evidence_json       JSONB NOT NULL,
    rule_id             VARCHAR(255) NOT NULL,
    rule_version        INTEGER NOT NULL,
    first_detected_at   TIMESTAMPTZ NOT NULL,
    last_detected_at    TIMESTAMPTZ NOT NULL,
    last_evaluated_at   TIMESTAMPTZ NOT NULL,
    resolved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_assessment_status
    ON assessment(status);

CREATE INDEX idx_assessment_scope
    ON assessment(scope_type, scope_id);

CREATE INDEX idx_assessment_code
    ON assessment(code);

CREATE INDEX idx_assessment_active_lookup
    ON assessment(correlation_key, status);

CREATE UNIQUE INDEX uq_assessment_active_correlation
    ON assessment(correlation_key)
    WHERE status = 'ACTIVE';
