CREATE TABLE crop (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species         VARCHAR(255) NOT NULL,
    variety         VARCHAR(255),
    location_id     VARCHAR(255) NOT NULL,
    planted_at      TIMESTAMPTZ NOT NULL,
    ended_at        TIMESTAMPTZ,
    status          VARCHAR(50) NOT NULL,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL,
    updated_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_crop_status ON crop(status);
CREATE INDEX idx_crop_location ON crop(location_id);
