CREATE TABLE goal (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id             BIGINT NOT NULL REFERENCES crop(id),
    goal_type           VARCHAR(50) NOT NULL,
    description         TEXT,
    status              VARCHAR(50) NOT NULL,
    priority            INTEGER,
    source_instruction  TEXT,
    metadata_json       JSONB NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_goal_crop ON goal(crop_id);
CREATE INDEX idx_goal_status ON goal(status);
