CREATE TABLE harvest (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id         BIGINT NOT NULL REFERENCES crop(id),
    harvested_at    TIMESTAMPTZ NOT NULL,
    quantity        DOUBLE PRECISION NOT NULL,
    unit            VARCHAR(20) NOT NULL,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_harvest_crop ON harvest(crop_id, harvested_at);
