CREATE TABLE crop_observation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id         BIGINT NOT NULL REFERENCES crop(id),
    metric          VARCHAR(50) NOT NULL,
    value_type      VARCHAR(20) NOT NULL,
    numeric_value   DOUBLE PRECISION,
    text_value      TEXT,
    boolean_value   BOOLEAN,
    unit            VARCHAR(50),
    source          VARCHAR(20) NOT NULL,
    confidence      DOUBLE PRECISION,
    observed_at     TIMESTAMPTZ NOT NULL,
    notes           TEXT,
    metadata_json   JSONB NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_crop_observation_crop ON crop_observation(crop_id, observed_at);
CREATE INDEX idx_crop_observation_metric ON crop_observation(metric);
