CREATE TABLE action (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crop_id         BIGINT NOT NULL REFERENCES crop(id),
    type            VARCHAR(20) NOT NULL,
    description     TEXT,
    quantity        DOUBLE PRECISION,
    unit            VARCHAR(20),
    performed_at    TIMESTAMPTZ NOT NULL,
    performed_by    VARCHAR(20) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_action_crop ON action(crop_id, performed_at);
